//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klienci
    {
        public Klienci()
        {
            this.Kontas = new HashSet<Konta>();
            this.Kredyties = new HashSet<Kredyty>();
            this.Lokaties = new HashSet<Lokaty>();
            this.Kody_Autoryzujace = new HashSet<Kody_Autoryzujace>();
        }
    
        public int id_klienta { get; set; }
        public long login { get; set; }
        public string haslo { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string pesel { get; set; }
        public string numer_dowodu { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public System.DateTime data_ur { get; set; }
        public Nullable<bool> blokada { get; set; }
        public int plec { get; set; }
    
        public virtual ICollection<Konta> Kontas { get; set; }
        public virtual ICollection<Kredyty> Kredyties { get; set; }
        public virtual ICollection<Lokaty> Lokaties { get; set; }
        public virtual ICollection<Kody_Autoryzujace> Kody_Autoryzujace { get; set; }
        public virtual Plcie Plcie { get; set; }
    }
}
