//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kody_Autoryzujace
    {
        public int id_kodu { get; set; }
        public string kod { get; set; }
        public int id_klienta { get; set; }
        public int numer_kodu { get; set; }
        public Nullable<bool> aktywny { get; set; }
    
        public virtual Klienci Klienci { get; set; }
    }
}
