//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kredyty
    {
        public Kredyty()
        {
            this.Raty_kredytu = new HashSet<Raty_kredytu>();
        }
    
        public int id_kredytu { get; set; }
        public int id_klienta { get; set; }
        public System.DateTime data_zawarcia { get; set; }
        public decimal kwota { get; set; }
        public int okres_kredytowania { get; set; }
        public double oprocentowanie { get; set; }
        public Nullable<double> rrso { get; set; }
        public Nullable<double> prowizja { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual ICollection<Raty_kredytu> Raty_kredytu { get; set; }
    }
}
