//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lokaty
    {
        public int id_lokaty { get; set; }
        public int id_klienta { get; set; }
        public System.DateTime data_rozpoczecia { get; set; }
        public decimal kwota { get; set; }
        public double oprocentowanie { get; set; }
        public int okres { get; set; }
        public string kapitalizacja { get; set; }
    
        public virtual Klienci Klienci { get; set; }
    }
}
