//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Entities : DbContext
    {
        public DB_Entities()
            : base("name=DB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Klienci> Kliencis { get; set; }
        public DbSet<Konta> Kontas { get; set; }
        public DbSet<Kredyty> Kredyties { get; set; }
        public DbSet<Lokaty> Lokaties { get; set; }
        public DbSet<Raty_kredytu> Raty_kredytu { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<typy_transakcji> typy_transakcji { get; set; }
        public DbSet<Kody_Autoryzujace> Kody_Autoryzujace { get; set; }
        public DbSet<Plcie> Plcies { get; set; }
        public DbSet<kategorie> kategories { get; set; }
        public DbSet<tokeny> tokenies { get; set; }
        public DbSet<Transakcje> Transakcjes { get; set; }
        public DbSet<Typy_Konta> Typy_Konta { get; set; }
        public DbSet<powiadomienia> powiadomienias { get; set; }
        public DbSet<Przelewy_Cykliczne> Przelewy_Cykliczne { get; set; }
    }
}
