//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plcie
    {
        public Plcie()
        {
            this.Kliencis = new HashSet<Klienci>();
        }
    
        public int id_plci { get; set; }
        public string nazwa { get; set; }
    
        public virtual ICollection<Klienci> Kliencis { get; set; }
    }
}
