//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Przelewy_Cykliczne
    {
        [Display(Name = "ID")]
        [Key]
        public int id_przelewu { get; set; }
        [RegularExpression(@"^\d+.\d{0,2}$", ErrorMessage = "Podałeś niepoprawną kwotę")]
        [Required(ErrorMessage = "Podaj kwotę transakcji.")]
        [Display(Name = "Kwota w zł")]
        public decimal kwota { get; set; }
        [Required(ErrorMessage = "Podaj datę realizacji przelewu.")]
        [DataType(DataType.Date)]
        [Display(Name = "Data realizacji przelewu ")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public System.DateTime data { get; set; }
        [Required(ErrorMessage = "Podaj tytuł przelewu.")]
        [StringLength(80, MinimumLength = 5, ErrorMessage = "Podaj od 5 do 50 znaków.")]
        [Display(Name = "Tytuł")]
        public string tytul { get; set; }
        [Required(ErrorMessage = "Wybierz typ transakcji.")]
        [Display(Name = "Typ transakcji")]
        public int typ_transakcji { get; set; }
        [Required(ErrorMessage = "Wybierz kategorię.")]
        [Display(Name = "Kategoria")]
        public int kategoria { get; set; }
        [Required(ErrorMessage = "Wybierz rachunek z jakiego chcesz zrealizować przelew.")]
        [Display(Name = "Wybierz rachunek: ")]
        [StringLength(26, MinimumLength = 26, ErrorMessage = "Numer konta musi się składać z 26 cyfr")]
        public string od_kogo { get; set; }
        [Required(ErrorMessage = "Wpisz numer konta na który chcesz zrealizować przelew.")]
        [Display(Name = "Podaj docelowy numer konta: ")]
        [StringLength(26, MinimumLength = 26, ErrorMessage = "Numer konta musi się składać z 26 cyfr")]
        public string do_kogo { get; set; }
        [Required(ErrorMessage = "Podaj dane osobowe odbiorcy.")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Podaj od 5 do 50 znaków.")]
        [Display(Name = "Dane odbiorcy")]
        public string dane_osobowe { get; set; }
        [Required(ErrorMessage = "Podaj swoje dane osobowe.")]
        [Display(Name = "Podaj swoje dane osobowe: ")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Podaj od 5 do 50 znaków.")]
        public string dane_osobowe_nadawca { get; set; }
        [Required(ErrorMessage = "Podaj poprawną liczbę dni")]
        [Display(Name = "Podaj co ile dni chciałbyś aby był wykonywany przelew: ")]
        public int co_ile_dni { get; set; }
    
        public virtual kategorie kategorie { get; set; }
        public virtual typy_transakcji typy_transakcji { get; set; }
    }
}
